#!/usr/bin/env python3
"""
export_standalone.py — build a single-file, double-click-anywhere HTML.

    python <skill>/scripts/export_standalone.py path/to/report.html
    → writes report-standalone.html next to it

Why: the folder deliverable (report.html + styles/ + assets/) is the canonical
working copy, but a recipient who double-clicks the HTML from a protected
folder (macOS Downloads, mail attachments, some intranets) may have every
sibling file blocked by the OS (net::ERR_ACCESS_DENIED) and see unstyled
text. The standalone export inlines EVERYTHING — CSS, fonts, logos, cover
art, copy.js — into one self-contained file (~5–6 MB because the Montserrat
TTFs ride along as data: URIs).

Rules:
  * Run ONLY AFTER check_brand.py has PASSED on the source report.html.
    This script refuses unresolved placeholders but is not the brand gate.
  * NEVER run check_brand.py against the standalone output — inline styles,
    scripts, and base64 images are lint failures by design in the WORKING
    file; the standalone is a generated build artifact, not a working file.
  * Never edit the standalone by hand; regenerate it from the source.
  * The PDF pipeline keeps using the folder version, never the standalone.
"""
from __future__ import annotations

import base64
import re
import sys
from pathlib import Path

MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".svg": "image/svg+xml", ".ttf": "font/ttf"}


def data_uri(path: Path) -> str:
    mime = MIME.get(path.suffix.lower())
    if not mime:
        raise ValueError(f"unsupported asset type: {path}")
    return f"data:{mime};base64,{base64.b64encode(path.read_bytes()).decode()}"


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    src = Path(sys.argv[1]).resolve()
    if not src.is_file():
        print(f"ERROR: {src} not found", file=sys.stderr)
        return 2
    base = src.parent
    html = src.read_text(encoding="utf-8")

    if re.search(r"{{\s*[A-Z_]+\s*}}", html):
        print("ERROR: unresolved {{PLACEHOLDER}} tokens — finish the report and pass "
              "check_brand.py before exporting.", file=sys.stderr)
        return 1

    # ---- inline the stylesheet (with fonts converted to data: URIs) -------
    css_path = base / "styles" / "report.css"
    if not css_path.is_file():
        print("ERROR: styles/report.css not found next to the HTML — export from the "
              "scaffolded folder, not a moved file.", file=sys.stderr)
        return 1
    css = css_path.read_text(encoding="utf-8")

    def font_repl(m: re.Match) -> str:
        rel = m.group(1)
        p = (css_path.parent / rel).resolve()
        if not p.is_file():
            raise FileNotFoundError(f"font referenced by CSS missing: {rel}")
        return f"url('{data_uri(p)}')"

    css = re.sub(r"url\('(\.\./assets/fonts/[^']+)'\)", font_repl, css)

    link_re = re.compile(r'<link[^>]+href="styles/report\.css"[^>]*>')
    if not link_re.search(html):
        print("ERROR: canonical stylesheet link not found — is this a scaffolded report?",
              file=sys.stderr)
        return 1
    html = link_re.sub(lambda _: f"<style>\n/* inlined from styles/report.css */\n{css}\n</style>", html, count=1)

    # ---- inline copy.js ----------------------------------------------------
    js_path = base / "assets" / "copy.js"
    if js_path.is_file():
        js = js_path.read_text(encoding="utf-8")
        html = re.sub(r'<script src="assets/copy\.js"[^>]*></script>',
                      lambda _: f"<script>\n/* inlined from assets/copy.js */\n{js}\n</script>",
                      html, count=1)

    # ---- inline every asset image ------------------------------------------
    def img_repl(m: re.Match) -> str:
        rel = m.group(1)
        p = base / rel
        if not p.is_file():
            raise FileNotFoundError(f"image referenced by HTML missing: {rel}")
        return f'src="{data_uri(p)}"'

    html = re.sub(r'src="(assets/[^"]+\.(?:png|jpe?g|svg))"', img_repl, html)

    dst = src.with_name(src.stem + "-standalone.html")
    banner = ("<!-- SELF-CONTAINED EXPORT — generated by export_standalone.py.\n"
              "     Do not edit by hand and do not run check_brand.py on this file;\n"
              "     regenerate from the canonical report.html instead. -->\n")
    html = html.replace("<!DOCTYPE html>", "<!DOCTYPE html>\n" + banner, 1)
    dst.write_text(html, encoding="utf-8")
    print(f"Standalone: {dst} ({dst.stat().st_size / 1_048_576:.1f} MB)")
    print("Share this single file freely — it renders identically from any folder, "
          "no sibling files needed. Keep using the folder version for PDF rendering.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
